{% set version = "4.1.0" %}

package:
  name: xraylib
  version: {{ version }}

source:
  url: http://lvserver.ugent.be/xraylib/xraylib-{{ version }}.tar.gz
  sha256: 3b6b07118153369f8d55b197fa8f341e38cb5fabc611deb576d2c805be5db7c4

build:
  number: 0

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pkg-config  # [unix]
    - cython
    - meson
    - ninja
    - swig
    - {{ compiler('fortran') }}  # [not win and not arm64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - test -f $PREFIX/include/xraylib/xraylib.mod  # [unix]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libxrl.pc exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\xrl.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\xraylib\\xraylib.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\xrl-11.dll exit 1  # [win]
  imports:
    - xraylib
    - xraylib_np

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: license_all.txt
  home: https://github.com/tschoonj/xraylib/wiki
  summary: A library for X-ray matter interaction cross sections for X-ray fluorescence applications

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - tschoonj
    - CJ-Wright
    - mrakitin
