{% set version = "3.2.0" %}

package:
  name: xraylib
  version: {{ version }}

source:
  fn: xraylib-{{ version }}.tar.gz
  url: https://xraylib.tomschoonjans.eu/xraylib-{{ version }}.tar.gz
  sha256: a734a0ea7b8224918f4e2105a4cf6c63664f257c1940a4c633beedf470d1576b
  patches:
    - conda-windows.patch  # [win]
    - xrayglob_inline.c.patch  # [win]
    - swig-fix.patch  # [win]

build:
  number: 0
  skip: False

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython
    - swig  # [not win]
    - autoconf  # [not win]
    - libtool  # [not win]
    - automake  # [not win]
    - m2-bash  # [win]
    - m2-autoconf  # [win]
    - m2-automake-wrapper  # [win]
    - m2-curl  # [win]
    - m2-grep  # [win]
    - m2-libtool  # [win]
    - m2-make  # [win]
    - m2-sed  # [win]
    - m2-which  # [win]
    - m2w64-binutils  # [win]
    - m2w64-pcre  # [win]
    - m2w64-gcc  # [win]
    - m2w64-toolchain  # [win]
    - m2w64-tools-git  # [win]

  run:
    - python
    - numpy x.x

test:
  commands:
    - xraylib  # [not win]
  imports:
    - xraylib
    - xraylib_np

about:
  license: BSD 3-Clause
  home: https://github.com/tschoonj/xraylib/wiki
  summary: A library for X-ray matter interaction cross sections for X-ray fluorescence applications

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - tschoonj
