{% set version = "3.2.0" %}

package:
  name: xraylib
  version: {{ version }}

source:
  fn: xraylib-{{ version }}.tar.gz
  url: https://github.com/tschoonj/xraylib/archive/xraylib-{{ version }}.tar.gz
  sha256: 4f4ab07f47619fa5458efbcd5ea51cd2c76c11a474ef869432235719c5bcdb41
  patches:
    - conda-windows.patch # [win]

build:
  number: 0
  skip: True  # [win32]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy >=0.7.0
    - cython
    - swig
    - autoconf # [not win]
    - libtool # [not win]
    - automake # [not win]
    - m2-bash # [win]
    - m2-autoconf # [win]
    - m2-automake-wrapper # [win]
    - m2-libtool # [win]
    - m2-make # [win]
    - m2w64-binutils # [win]
    - m2w64-gcc # [win]

  run:
    - python
    - numpy x.x
    - scipy >=0.7.0

test:
  commands:
    - xraylib # [not win]
  imports:
    - xraylib

about:
  license: BSD 3-Clause
  home: https://github.com/tschoonj/xraylib/wiki
  summary: A library for X-ray matter interaction cross sections for X-ray fluorescence applications

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - tschoonj
