{% set version = "4.1.2" %}

package:
  name: xraylib
  version: {{ version }}

source:
  url: http://lvserver.ugent.be/xraylib/xraylib-{{ version }}.tar.gz
  sha256: d0165fa1a7bf63760b94650c26ff3783020c652b96fdf8373eb758af663a7c13

build:
  number: 2
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
  run_exports:
    - {{ pin_subpackage('xraylib', max_pin='x') }}

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pkg-config  # [unix]
    - cython
    - meson
    - ninja
    - swig
    - {{ compiler('fortran') }}  # [not win and not arm64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ucrt  # [win]

test:
  commands:
    - test -f $PREFIX/include/xraylib/xraylib.mod  # [unix]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libxrl.pc exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\xrl.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\xraylib\\xraylib.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\xrl-11.dll exit 1  # [win]
  imports:
    - xraylib
    - xraylib_np

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: license_all.txt
  home: https://github.com/tschoonj/xraylib/wiki
  summary: A library for X-ray matter interaction cross sections for X-ray fluorescence applications

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - tschoonj
    - CJ-Wright
    - mrakitin
