{% set version = "4.1.4" %}

package:
  name: xraylib
  version: {{ version }}

source:
  url: https://github.com/tschoonj/xraylib/releases/download/xraylib-{{ version }}/xraylib-{{ version }}.tar.gz
  sha256: b0d77b186e3bf83cc5be29d687cf6225f94276233f257d4f855e9ef61a9c14d5
  patches:
    - numpy-2.patch

build:
  number: 1
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
  run_exports:
    - {{ pin_subpackage('xraylib', max_pin='x') }}

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - numpy
    - pkg-config  # [unix]
    - cython
    - meson
    - ninja
    - swig
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - ucrt  # [win]

test:
  commands:
    - test -f $PREFIX/include/xraylib/xraylib.mod  # [unix]
    - if not exist %LIBRARY_INC%\\xraylib\\xraylib.mod exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libxrl.pc exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\xrl.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\xraylib\\xraylib.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\xrl-11.dll exit 1  # [win]
  imports:
    - xraylib
    - xraylib_np

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: license_all.txt
  home: https://github.com/tschoonj/xraylib/wiki
  summary: A library for X-ray matter interaction cross sections for X-ray fluorescence applications

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - tschoonj
    - CJ-Wright
    - mrakitin
