appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: woonV/7BOhf7Gih+J94IAR/YTnxp7l5Jhw3Aub/IK946vFYuRZgGOkOIZickBl5mtyOS+wBXIPG//pMPoyLdzDqGa13j9rbKibhsUBtha8RQGHsb/zfRBSKpk6SubrVn9ghtD+0iDK+nQ9DHodRoZwNqWHRIP1sNEWjzVkKfvJ1uvBm/59PQtHcoGVnGh+5x8QonQV7xhlIGie1rslcZ5rmOX5ZN86tQ8QvkEZ9ia8CLuyHJxPPRMP943YAdVJ/6riVV+xGtEM38lH/RSK6wmSN6sqFlJpAQXf8CkDXJ2F8MzgGXzM9dWIqXuHJ/Yj/4bwMCwuppdkFAZkVe/ThKVWWYdQ5IUlZHBS/2Y/OoDAqhd8labOcZQxU79Smm3zgntp7Ti/vIWgVv4xnVqOq2YAWZEAAbu7cK24YeT7pkcUym9Mkpnpw1df0Ep/QQz0qTBANS1s56+rFf74cdKsVqHSWlzq9vHV2gRBLSGpDHJ9Yan9YzmwgpnYhx3oEiS1oKkPXpL3Si8CYgMPotxl/G3btwjAjXR2mzIqoDQiRV7HDgsaE81hWqXJybKa8wlBa5OolbofHadYlYBMnc7h9FIfDBnA5vrHahWZJPV6E6Mn8ET45GKn5jCBXp/0Ef2h6c4Zpj6IJmplKAdctoNZY+/jk/A80fajy1+761v3R6woE=}
provider:
  win: azure
conda_forge_output_validation: true
